
import { UnitType, BuildingType, CRUSHER_ANGLE } from './types';

export const TICK_RATE = 1000 / 60; // 60 FPS target logic

export const COST_SCALING_FACTOR = 1.15; // Each unit costs 15% more than the previous one of that type

export const UNIT_STATS: Record<UnitType, { cost: number; speed: number; capacity: number; power: number; maxEnergy: number; label: string; isTool?: boolean }> = {
  [UnitType.MINER_BASIC]: { cost: 10, speed: 0.8, capacity: 5, power: 0.5, maxEnergy: 100, label: 'Miner' },
  [UnitType.MINER_DRILL]: { cost: 250, speed: 0, capacity: 0, power: 5, maxEnergy: 500, label: 'Hvy Drill', isTool: true }, // Speed 0 means it cannot move on its own
  [UnitType.CARRIER_ROVER]: { cost: 50, speed: 1.5, capacity: 15, power: 2, maxEnergy: 150, label: 'Speedy Bot' },
  [UnitType.CARRIER_DRONE]: { cost: 500, speed: 3, capacity: 40, power: 4, maxEnergy: 120, label: 'Flying Drone' },
};

export const BUILDING_COSTS: Record<BuildingType, { baseCost: number; scale: number; label: string; desc: string }> = {
  [BuildingType.DORMITORY]: { baseCost: 100, scale: 1.5, label: 'Habitat', desc: 'Increases population cap (+5)' },
  [BuildingType.WORKSHOP]: { baseCost: 500, scale: 2.0, label: 'Tech Lab', desc: 'Allows advanced unit production' },
  [BuildingType.CRUSHER]: { baseCost: 1500, scale: 1.5, label: 'Ore Crusher', desc: 'Passive ore processing' },
  [BuildingType.REACTOR]: { baseCost: 5000, scale: 2.5, label: 'Core Reactor', desc: 'Speed up all units' },
};

// Which units can be recruited at which building
export const UNIT_UNLOCKS: Record<BuildingType, UnitType[]> = {
  [BuildingType.DORMITORY]: [UnitType.MINER_BASIC, UnitType.CARRIER_ROVER],
  [BuildingType.WORKSHOP]: [UnitType.MINER_DRILL, UnitType.CARRIER_DRONE],
  [BuildingType.CRUSHER]: [],
  [BuildingType.REACTOR]: [],
};

// Definitions for specific building upgrades
export interface BuildingUpgrade {
    id: string;
    label: string;
    cost: number;
    desc: string;
    effect?: { maxWorkersAdd?: number };
}

export const BUILDING_UPGRADES: Record<BuildingType, BuildingUpgrade[]> = {
    [BuildingType.CRUSHER]: [
        { id: 'crusher_slot_1', label: 'Manual Input', cost: 1000, desc: 'Adds a worker slot to boost production.', effect: { maxWorkersAdd: 1 } },
        { id: 'crusher_slot_2', label: 'Sorting Gear', cost: 5000, desc: 'Adds a second worker slot.', effect: { maxWorkersAdd: 1 } },
        { id: 'crusher_slot_3', label: 'Hydraulics', cost: 15000, desc: 'Adds a third worker slot.', effect: { maxWorkersAdd: 1 } }
    ],
    [BuildingType.DORMITORY]: [],
    [BuildingType.WORKSHOP]: [],
    [BuildingType.REACTOR]: []
};

// Kept for backward compat logic if needed, but mainly driven by upgrades now
export const UPGRADE_COSTS: Record<BuildingType, number> = {
    [BuildingType.DORMITORY]: 500,
    [BuildingType.WORKSHOP]: 2000,
    [BuildingType.CRUSHER]: 1000, 
    [BuildingType.REACTOR]: 10000,
};

export const ORE_VALUE = 1; // Credits per ore
// BASE_CRUSHER_RATE removed, unified into building loop (15 per crusher)
export const CRUSHER_WORKER_BONUS = 20; // Extra ore per second if worker is present (scaled by energy)
export const BASE_POPULATION = 0;
export const POPULATION_PER_HABITAT = 5;
export const ENERGY_DRAIN_RATE = 3; // Energy lost per second while working
export const ENERGY_RECHARGE_RATE = 25; // Energy gained per second while charging
export const BUILD_SPEED_BASE = 0.2; // Progress per second per unit power
export const DRILL_WEIGHT_SPEED_PENALTY = 0.4; // Speed multiplier when carrying a drill
export const DRILL_PRODUCTION_RATE = 20; // Ore per second generated by heavy drill

// Generate slots around the asteroid
const slots = [];

// 1. MAIN CRUSHER (ID 0)
slots.push({
    id: 0,
    angle: CRUSHER_ANGLE,
    type: BuildingType.CRUSHER,
    level: 1,
    unlocked: true,
    status: 'COMPLETED',
    constructionProgress: 1,
    assignedUnitId: null,
    occupants: [],
    maxWorkers: 0, 
    assignedWorkers: [],
    requestedWorkers: 0,
    upgrades: []
});

// 2. Empty Slots
const START_ANGLE = 50;
const END_ANGLE = 340; // Equivalent to -20
const STEP = 30;
let idCounter = 1;

for (let angle = START_ANGLE; angle <= END_ANGLE; angle += STEP) {
    slots.push({ 
      id: idCounter++, 
      angle: angle, 
      type: null, 
      level: 0, 
      unlocked: true,
      status: 'EMPTY',
      constructionProgress: 0,
      assignedUnitId: null,
      occupants: [],
      maxWorkers: 0,
      assignedWorkers: [],
      requestedWorkers: 0,
      upgrades: []
    });
}

export const INITIAL_SLOTS = slots;
